Order of annotation sets in tag detail pages
AVAnnotate/project-client pull request #125
Opened 2024-12-23 21:49 UTC by ajolipa

### In this PR
Quick and dirty fix for the fact that annotations sets are being displayed in an apparently nonsensical order on the various tag detail pages. This fix should have them ordered alphabetically by event label and then alphabetically by set name.

2024-12-23 21:55 UTC, lwjameson approved these changes
Looks good

2024-12-23 22:10 UTC, camdendotlol requested changes
Just one minor change request. Feel free to merge when it's done since I won't be around to approve.

2024-12-23 22:10 UTC, camdendotlol commented on src/utils/tags.ts
> +    return event_a.data.label < event_b.data.label
Comparing strings with `<` and `>` is case-sensitive:

```js
const letters = ['A', 'a', 'B', 'z', 'Z']

console.log(letters.sort())
// ["A", "B", "Z", "a", "z"]

console.log('a' > 'b') // false
console.log('a' > 'B') // true
```

Converting the labels to lowercase before comparing would prevent unexpected sorting behavior.

2024-12-26 21:38 UTC, ajolipa commented on src/utils/tags.ts
> +    return event_a.data.label < event_b.data.label
Done, good call.

2024-12-26 21:39 UTC, merged