Added video functionality
AVAnnotate/project-client pull request #15
Opened 2024-09-16 01:16 UTC by ajolipa

### In this PR
- Adds basic video player capability 
![image](https://github.com/user-attachments/assets/62c2851e-948d-47ac-a602-95c0517632ed)

NOTE: Styling/layout still not fully tested in the case that there are actually some annotations, but at least the video is playing nicely!

(Should be merged after PR #14 )

2024-09-16 12:53 UTC, camdendotlol requested changes
Just a couple `console.log`s to remove and a question.

2024-09-16 12:53 UTC, camdendotlol commented on src/pages/events/[pageUuid].astro
> +                    event.data.item_type.toLowerCase() == 'video'
The `item_type` value created by the admin client is always capitalized (`Video` or `Audio`). Do you have test data where it appears in all lower-case?

2024-09-16 12:53 UTC, camdendotlol commented on src/components/AnnotationUI/TagFilter.tsx
> +    console.log(current.length, tags[category].tags.length);
remove `console.log`

2024-09-16 12:53 UTC, camdendotlol commented on src/components/AnnotationUI/TagFilter.tsx
> +    console.log(updated);
remove `console.log`

2024-09-16 14:05 UTC, ajolipa commented on src/pages/events/[pageUuid].astro
> +                    event.data.item_type.toLowerCase() == 'video'
No, I just wasn't sure and was scarred after running into case inconsistencies in the tag categories haha. If you're confident that it can only ever be capitalized, I'll change this accordingly.

2024-09-16 14:09 UTC, ajolipa commented on src/components/AnnotationUI/TagFilter.tsx
> +    console.log(current.length, tags[category].tags.length);
Done

2024-09-16 14:10 UTC, ajolipa commented on src/components/AnnotationUI/TagFilter.tsx
> +    console.log(updated);
Done

2024-09-16 14:51 UTC, camdendotlol commented on src/pages/events/[pageUuid].astro
> +                    event.data.item_type.toLowerCase() == 'video'
The admin site only tests for the capitalized versions so it would be better to be consistent with that behavior. In the future we could have an item type equivalent of https://github.com/AVAnnotate/admin-client/issues/83 though

2024-09-16 14:51 UTC, camdendotlol approved these changes

2024-09-17 14:38 UTC, lwjameson approved these changes

2024-09-18 19:09 UTC, closed without merging