Event embeds in custom pages
AVAnnotate/project-client pull request #21
Opened 2024-09-20 18:48 UTC by camdendotlol

# Summary

This PR turned into more of a kitchen sink than I originally planned.

- refactors the event viewer component to only require one prop (`uuid`, the UUID of the event) and to do all the data fetching on its own so we can share it in multiple places
- updates the new/refactored `Event` component to accept several optional props that will be passed in by embedded event Slate nodes
  - adds support for the `includes` prop, which determines which parts of the component should be displayed
  - does not add any handling for the `start` and `end` props, which should eventually determine which portions of an audiovisual file to include in the embed
- adds Zod schemas for pages and events
  - these might need to updated to accommodate changes in the data or any fields that might have been missing from my sample data, as Astro validates the JSON files based on these schemas and will complain if they don't match
- adds new helper functions to `src/utils/pages.ts` that provide a type-safe way to fetch pages and the page order file. This was necessary because Zod picks up that there are two types of pages (normal pages + the order file) and will treat any page as potentially being either one unless we do some typecasting
- removes the "copy timestamp" tooltip button from the player and uninstalls all associated packages - it was part of the admin client's design, but not the project client

2024-09-20 19:52 UTC, ajolipa requested changes
Looks awesome, just a handful of little things I think need tweaking.

2024-09-20 19:52 UTC, ajolipa commented on src/layouts/Layout.astro
We need the `bg-gray-100` on `main`, otherwise it becomes black on screens bigger than 3xl. Might be redundant to also have it on `body` I guess.

2024-09-20 19:52 UTC, ajolipa commented on src/content/config.ts
I think that everything that's `.optional()` here should be `.nullish()` to allow for `null` values; at least with the existing sample data that I have, there are cases where optional fields are explicitly defined as `null` in the data JSON files, and `.optional()` doesn't like that.

2024-09-20 19:52 UTC, ajolipa commented on src/pages/events/[pageUuid].astro
`Event` component here should be `sticky`.

2024-09-23 14:30 UTC, camdendotlol commented on src/layouts/Layout.astro
I've refactored how we style the page backgrounds to account for the difference in color between events and custom pages.

I removed the black `body` background under the assumption that it was unintended (there's nothing with a black background in the Figma designs?), as well as the `3xl` size limit for the `Layout`. I can add those back if needed.

2024-09-23 19:12 UTC, camdendotlol commented
@ajolipa This is ready for re-review. My latest commit includes some Prettier formatting (the Header and Footer haven't been touched since we enabled formatting).

2024-09-23 20:55 UTC, ajolipa approved these changes
Looks good!

2024-09-23 21:07 UTC, merged